/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
    const group = useRef();
    useFrame(({ clock }) => {
        const a = clock.getElapsedTime();
        group.current.rotation.y = a / 2;
        // group.current.rotation.x = a / 2;
      });
    const { nodes, materials } = useGLTF("/goldenStar.glb");
    return (
      <group ref={group} {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.TopLid}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials.BottomLid}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials.Side}
        />
      </group>
    );
  }

useGLTF.preload("../../goldenStar.glb");
