/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF("../../untitled.glb");
  const myMesh = useRef();
  
  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    myMesh.current.rotation.y = a / 2;
  });
  return (
    <group ref={myMesh} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sgushenka.geometry}
        material={materials.Trans_Mat}
      />
    </group>
  );
}

useGLTF.preload("../../untitled.glb");
